language: generic
branches:
  only:
    - master
services:
  - docker
sudo: required
script:
  - DOCKER=1 make test build docker-build
deploy:
  provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
