language: go
go:
  - 1.6.0
branches:
  only:
    - master
cache:
  directories:
    - vendor
services:
  - docker
sudo: required
install:
  - curl https://storage.googleapis.com/goprojects/glide-0.10.2-linux-amd64 > glide
  - chmod +x ./glide
  - ./glide install
script:
  - go test $(./glide nv)
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o rootfs/bin/goprox
  - make docker-build
deploy:
  provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
