apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  labels:
    heritage: deis
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  aws-access-key-id: "{{.Values.awsAccessKeyID | b64enc}}"
  aws-secret-key: "{{.Values.awsSecretKey | b64enc}}"
