// Code generated by protoc-gen-go.
// source: admin.proto
// DO NOT EDIT!

/*
Package admin is a generated protocol buffer package.

It is generated from these files:
	admin.proto

It has these top-level messages:
	PackageList
	Package
	Empty
*/
package admin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type PackageList struct {
	Packages []*Package `protobuf:"bytes,1,rep,name=packages" json:"packages,omitempty"`
}

func (m *PackageList) Reset()                    { *m = PackageList{} }
func (m *PackageList) String() string            { return proto.CompactTextString(m) }
func (*PackageList) ProtoMessage()               {}
func (*PackageList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PackageList) GetPackages() []*Package {
	if m != nil {
		return m.Packages
	}
	return nil
}

type Package struct {
	Name string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*PackageList)(nil), "admin.PackageList")
	proto.RegisterType((*Package)(nil), "admin.Package")
	proto.RegisterType((*Empty)(nil), "admin.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Admin service

type AdminClient interface {
	GetPackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageList, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetPackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageList, error) {
	out := new(PackageList)
	err := grpc.Invoke(ctx, "/admin.Admin/GetPackages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Admin service

type AdminServer interface {
	GetPackages(context.Context, *Empty) (*PackageList, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_GetPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/GetPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetPackages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPackages",
			Handler:    _Admin_GetPackages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0xc9, 0xcd,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x2c, 0xb9, 0xb8, 0x03,
	0x12, 0x93, 0xb3, 0x13, 0xd3, 0x53, 0x7d, 0x32, 0x8b, 0x4b, 0x84, 0xb4, 0xb8, 0x38, 0x0a, 0x20,
	0xdc, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x3e, 0x3d, 0x88, 0x2e, 0xa8, 0xaa, 0x20,
	0xb8, 0xbc, 0x92, 0x2c, 0x17, 0x3b, 0x54, 0x50, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x15,
	0xa8, 0x85, 0x51, 0x83, 0x33, 0x88, 0x25, 0x0f, 0xc8, 0x56, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d,
	0x28, 0xa9, 0x34, 0xb2, 0xe2, 0x62, 0x75, 0x04, 0x19, 0x21, 0x64, 0xc8, 0xc5, 0xed, 0x9e, 0x5a,
	0x02, 0xd5, 0x53, 0x2c, 0xc4, 0x03, 0x35, 0x19, 0xac, 0x4a, 0x4a, 0x08, 0xd5, 0x1e, 0x90, 0x6b,
	0x94, 0x18, 0x92, 0xd8, 0xc0, 0x8e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x15, 0xff,
	0x0c, 0xbb, 0x00, 0x00, 0x00,
}
